name: 'olist'
version: '1.0.0'
profile: 'olist'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist:
    staging:
      +schema: staging
      +materialized: view
    mart:
      +schema: mart
      +materialized: table